--- 
extensions: 
- json
- another-extension
name: iscrollDemo
wp: 
  productid: c2f9ed90-350e-012f-77e2-444619957129
bbver: 4.6
sdk: C:/Spritle/setup/RhoStudio/ruby/lib/ruby/gems/1.8/gems/rhodes-3.2.3
android: 
  version: 2.2
  emulator: samsung
applog: rholog.txt
build: debug
wmsdk: Windows Mobile 6 Professional SDK (ARMV4I)
version: 1.0
symbian: 
  uid: "0xeb605f46"
vendor: rhomobile
sdkversion: 3.2.1
iphone: 
  BundleURLScheme: iscrolldemo
  provisionprofile: 
  BundleIdentifier: com.rhomobile.iscrolldemo
  sdk: iphonesimulator5.0
  entitlements: 
  codesignidentity: 
  configuration: Release
